import Head from 'next/head'
import { Inter } from '@next/font/google'
import Splash from '@/components/Splash'
import Principal from '@/components/Principal'
import About from '@/components/About'
import Navbar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>PLANTASIA</title>
        
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Splash/>
      <main>
        <Navbar/>
        <Principal/>
        <About/>
      </main>
    </>
  )
}
